# Generated by Django 3.2.5 on 2021-08-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210810_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tiltle',
            new_name='title',
        ),
    ]
