# Generated by Django 3.2.5 on 2021-09-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210903_1419'),
        ('catalog', '0006_auto_20210903_1451'),
    ]

    operations = [
    ]
